        Hiệu Suất Games Performance + Tăng tốc CPU 
cmd device_config put activity_manager open_gl_gpu_performance  enable
cmd device_config put activity_manager force_cpu_performance  enable
cmd device_config put activity_manager force_gpu_performance  enable
cmd device_config put activity_manager force_gpu_driver_performance  true
cmd device_config put activity_manager ro.kernel.checkjni  0
cmd device_config put activity_manager ro.cpu.vendor.performance  enable
cmd device_config put activity_manager ro.gpu.vendor.performance  enable
cmd device_config put activity_manager ro.kernel.android.checkjni 0
cmd device_config put activity_manager persist.sys.meow.gr.swapinterval -1
cmd device_config put activity_manager ril.product_code meow_mediatek 
cmd device_config put activity_manager ro.cfg.custom.sw_limit 300
cmd device_config put activity_manager ro.config.dha.fps_max 60
cmd device_config put activity_manager sys.perf.tbooster true
cmd device_config put activity_manager hwui.disable_vsync true
cmd device_config put activity_manager hwui.render_dirty_regions false
cmd device_config put activity_manager debug.sf.no_hw_vsync 0
cmd device_config put activity_manager debug.hwui.use_buffer_age false
cmd device_config put activity_manager hwui.use_gpu_pixel_buffers true
cmd device_config put activity_manager ro.bq.gpu_to_cpu_unsupported 1
cmd device_config put activity_manager debugtool.anrhistory 0
cmd device_config put activity_manager persist.sys.ssr.restart_level 1
cmd device_config put activity_manager persist.sys.ap.restart_level 1
cmd device_config put activity_manager persist.cpu.gov.performance true
cmd device_config put activity_manager persist.gpu.gov.performance true
cmd device_config put activity_manager ro.allow.mock.location 0
cmd device_config put activity_manager persist.sys.ui.hw 1
cmd device_config put activity_manager ro.ril.sensor.sleep.control 1
cmd device_config put activity_manager ro.compcache.default 0
cmd device_config put activity_manager ro.ext4fs 1
cmd device_config put activity_manager ro.config.hw_power_saving 1
cmd device_config put activity_manager ro.mot.buttonlight.timeout 1
cmd device_config put activity_manager power_supply.wakeup enable
cmd device_config put activity_manager debug.egl.buffcount "4"
cmd device_config put activity_manager debug.cpurend.vsync "false"
cmd device_config put activity_manager debug.gpurend.vsync "false"
cmd device_config put activity_manager persist.service.lgospd.enable 0
cmd device_config put activity_manager persist.service.pcsync.enable 0
cmd device_config put activity_manager force.system.fps "true"
cmd device_config put activity_manager game.accelerate.hw "1"
cmd device_config put activity_manager persist.sys.NV_POWERMODE "1"
cmd device_config put activity_manager sys.hwc.gpu_perf_mode 1
cmd device_config put activity_manager debug.sf.enable_advanced_sf_phase_offset 1
cmd device_config put activity_manager ro.vendor.qti.core.ctl_max_cpu 8
cmd device_config put activity_manager ro.vendor.qti.core.ctl_min_cpu 4
cmd device_config put activity_manager profiler.debugmonitor false
cmd device_config put activity_manager ro.config.hw_fast_dormancy 1
cmd device_config put activity_manager ro.game.access.gpu.driver 1
cmd device_config put activity_manager cpu_framerate_per_sec 60.0
cmd device_config put activity_manager gpu_framerate_per_sec 60.0
cmd device_config put activity_manager persist.sys.dalvik.hyperthreading true
cmd device_config put activity_manager fstrim_mandatory_interval "1"
cmd device_config put activity_manager ro.hwui.use_opengl "true"
cmd device_config put activity_manager ro.hwui.use_vulkan "true"
cmd device_config put activity_manager gpu_debug_layers_gles  "EGL_KHR_gl_texture_cubemap_image,EGL_KHR_gl_texture_3D_image,EGL_KHR_gl_renderbuffer_image"
cmd device_config put activity_manager debug.sf.disable_backpressure 1
cmd device_config put activity_manager debug.sf.latch_unsignaled 1  
cmd device_config put activity_manager debug.sf.enable_hwc_vds 1
cmd device_config put activity_manager debug.sf.early_phase_offset_ns 1  
cmd device_config put activity_manager debug.sf.early_app_phase_offset_ns 1
cmd device_config put activity_manager debug.sf.early_gl_phase_offset_ns 1
cmd device_config put activity_manager debug.sf.early_gl_app_phase_offset_ns 1
cmd device_config put activity_manager debug.sf.high_fps_early_phase_offset_ns 1
cmd device_config put activity_manager debug.sf.high_fps_early_gl_phase_offset_ns 1
cmd device_config put activity_manager debug.sf.high_fps_late_app_phase_offset_ns 1
cmd device_config put activity_manager debug.sf.phase_offset_threshold_for_next_vsync_ns 1
cmd device_config put activity_manager quickstar_qs_tile_layout_custom_matrix 1
cmd device_config put activity_manager ro.system.graphics_driver enable
cmd device_config put activity_manager config_per_process_gpu_memory_fraction 0.9
cmd device_config put activity_manager config_cpu_options_allow_growth true
cmd device_config put activity_manager config_gpu_options_allow_growth true

